### PR TITLE
lock: added return statement to lock acquire.

### PR DESCRIPTION
**Pull request by alejandromumo**
closes https://github.com/zenodo/rdm-project/issues/464

### CODE REVIEW

**Review by kpsherva — APPROVED** [review]
LGTM! but I am not very experienced with this, better if we have second reviewer

**Comment by alejandromumo** [comment]
> LGTM! but I am not very experienced with this, better if we have second reviewer

The issue here is that moderation's tasks use `lock_or_renew` (from the lock base implementation), which checks the return value of `lock.acquire`. Without a return statement, it's always `None` and fails to execute moderation tasks (e.g. reindex records after approve)

**Comment by kpsherva** [comment]
> > LGTM! but I am not very experienced with this, better if we have second reviewer
> 
> The issue here is that moderation's tasks use `lock_or_renew` (from the lock base implementation), which checks the return value of `lock.acquire`. Without a return statement, it's always `None` and fails to execute moderation tasks (e.g. reindex records after approve)

I understand the change, however I don't know why we are using the lock_or_renew for the moderation actions, this is why I might not be fully aware of the consequences of the change.

**Review by slint — APPROVED** [review]

**Comment by slint** [comment]
After discussing IRL with @alejandromumo, I think the overall "behaviour" of the locks is a bit funky right now indeed, but I would separate this into a different issue and just have this PR be a bug fix.

**Pull request merged**
